# http://webui.me
# https://github.com/webui-dev/webui
# Copyright (c) 2020-2023 Hassan Draga.
# Licensed under MIT License.
# All rights reserved.
#
# Special Thanks to Turiiya (https://github.com/ttytm)

name: Linux
on:
  workflow_call:

jobs:
  build_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - name: build_examples
        run: zig build build_all
      - name: build_examples_dynamic
        run: zig build build_all -Dis_static=false

  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: build_examples
        run: zig build build_all
      - name: build_examples_dynamic
        run: zig build build_all -Dis_static=false
